
package view;
import dao.DaoAlimentoImp;
import dao.DaoBebidaImp;
import model.Pedido;
import javax.swing.JOptionPane;
import dao.DaoPedidoImp;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Kamila Monaris
 */
public class FrmCadPedido extends javax.swing.JInternalFrame {
    DaoPedidoImp dao = new DaoPedidoImp();
    DaoAlimentoImp daocomboo = new DaoAlimentoImp();
    DaoBebidaImp daocombo = new DaoBebidaImp();
    List<Pedido> pedi = new ArrayList<Pedido>();
    List<String> combo = new ArrayList<String>();
    List<String> comboo = new ArrayList<String>();
 
    int id= 0;
    int indice = 0;
    Pedido pedido;
    
    public void mostrarDados(){
        txtId.setText(""+pedi.get(indice).getId());
        txtId.setText(""+pedi.get(indice).getId());
        cbxPrato.setSelectedItem(pedi.get(indice).getPrato());
        cbxBebida.setSelectedItem(pedi.get(indice).getBebida());
        txtData.setText(pedi.get(indice).getData());
        txtValor.setText(pedi.get(indice).getValor());
        
    } 
    
    public FrmCadPedido() {
        initComponents();
        txtId.setEditable(false);
        pedi = dao.getPedido();
        combo = daocombo.carregaCombo();
        comboo = daocomboo.carregaComboo();
        
        while(!combo.isEmpty() && !comboo.isEmpty())
        {
        cbxPrato.addItem(comboo.get(0));
        cbxBebida.addItem(combo.remove(0));
        combo.remove(0);
        comboo.remove(0);
        }
        
        while(!combo.isEmpty())
        {
        cbxBebida.addItem(combo.get(0));
        combo.remove(0);
        }
        
        if(pedi.isEmpty()){
        JOptionPane.showMessageDialog(null,"Não existe pedidos cadastrados");
        }
        else{
        //mostrarDados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPedido = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPrato = new javax.swing.JLabel();
        lblBabida = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        cbxPrato = new javax.swing.JComboBox<>();
        cbxBebida = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        PainelPedido.setBackground(new java.awt.Color(255, 204, 153));

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTitulo.setText("Cadastro de Pedidos");

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("Id:");

        lblPrato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPrato.setText("Prato:");

        lblBabida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBabida.setText("Bebida:");

        lblData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblData.setText("Data:");

        lblValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblValor.setText("Valor:");

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        cbxPrato.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxPrato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Selecionar ----" }));

        cbxBebida.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbxBebida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---- Selecionar ----" }));

        txtData.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtData.setText("  /  /");

        txtValor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValor.setText("R$ ");
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelPedidoLayout = new javax.swing.GroupLayout(PainelPedido);
        PainelPedido.setLayout(PainelPedidoLayout);
        PainelPedidoLayout.setHorizontalGroup(
            PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPedidoLayout.createSequentialGroup()
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPedidoLayout.createSequentialGroup()
                        .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelPedidoLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBabida)
                                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblValor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrato, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(PainelPedidoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPedidoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelPedidoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnPrimeiro)
                        .addGap(37, 37, 37)
                        .addComponent(btnAnterior))
                    .addGroup(PainelPedidoLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(lblTitulo))
                    .addGroup(PainelPedidoLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnProximo)
                        .addGap(30, 30, 30)
                        .addComponent(btnUltimo)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        PainelPedidoLayout.setVerticalGroup(
            PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPedidoLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrato)
                    .addComponent(cbxPrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBabida)
                    .addComponent(cbxBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro)
                    .addComponent(btnAnterior)
                    .addComponent(btnProximo)
                    .addComponent(btnUltimo))
                .addGap(30, 30, 30)
                .addGroup(PainelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if(pedi.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não existe pedido cadastrados");    
        }
        else{
        indice = 0;
        txtId.setText(""+pedi.get(indice).getId());
        cbxPrato.setSelectedItem(pedi.get(indice).getPrato());
        cbxBebida.setSelectedItem(pedi.get(indice).getBebida());
        txtData.setText(pedi.get(indice).getData());
        txtValor.setText(pedi.get(indice).getValor());
        
        }
        
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
       if(pedi.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existe pedido cadastrados");
        }
        else{
            indice--;
        }
        if(indice<0){
            indice++;
            JOptionPane.showMessageDialog(null, "Você já esta no primeiro registro");
        }
        mostrarDados();
        btnProximo.setEnabled(true);
        
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if(pedi.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existe pedidos cadastrados");
        }
        else{
            indice++;
        }
        if(indice>pedi.size()-1){
            indice--;
            JOptionPane.showMessageDialog(null, "Você ja esta no ultimo registro");
        }
        mostrarDados();
        
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if(pedi.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não existe pedidos cadastrados");    
        }
        else{
        indice=pedi.size()-1;
        mostrarDados();
        btnProximo.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        if(pedi.isEmpty()){
            id = 1;
        }
        else{
            id = pedi.get(pedi.size()-1).getId()+1;
        }
        txtId.setText(""+id);
        cbxPrato.setSelectedItem("");
        cbxBebida.setSelectedItem("");
        txtData.setText("");
        txtValor.setText("");
        
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        pedido = new Pedido();
        pedido.setId(Integer.parseInt(txtId.getText()));
        pedido.setPrato(cbxPrato.getSelectedItem().toString());
        pedido.setBebida(cbxBebida.getSelectedItem().toString());
        pedido.setData(txtData.getText());
        pedido.setValor(txtValor.getText());
        
        dao.SalvarPedido(pedido);
        pedi = dao.getPedido();
        indice = pedi.size()-1;
        mostrarDados();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        dao.ExcluirPedido(Integer.parseInt(txtId.getText()));
        if(pedi.isEmpty()){
           txtId.setText(""+pedi.get(indice).getId());
           txtId.setText(""+pedi.get(indice).getId());
           cbxPrato.setSelectedItem(pedi.get(indice).getPrato());
           cbxBebida.setSelectedItem(pedi.get(indice).getBebida());
           txtData.setText(pedi.get(indice).getData());
           txtValor.setText(pedi.get(indice).getValor());
       }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(pedi.isEmpty())
        {
        txtId.setText("");
        txtData.setText("");
        txtValor.setText("");
        }else
        {
            int opcao = JOptionPane.showConfirmDialog(null, "Tem ceteza que deseja excluir o pedido","Confirmação",JOptionPane.YES_NO_OPTION);
            if(opcao ==0)
            {
                dao.ExcluirPedido(Integer.parseInt(txtId.getText()));
                pedi.clear();
                pedi = dao.getPedido();
                indice=pedi.size()-1;
                mostrarDados();
                
            }
            else
            JOptionPane.showMessageDialog(null, "Não foi excluído");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPedido;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbxBebida;
    private javax.swing.JComboBox<String> cbxPrato;
    private javax.swing.JLabel lblBabida;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPrato;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
