/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Usuario;
import dao.DaoUsuarioImp;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Kamila Monaris
 */
public class FrmCadUsuario extends javax.swing.JInternalFrame {
    DaoUsuarioImp dao = new DaoUsuarioImp();
    List<Usuario> usu = new ArrayList<Usuario>();
    
    int id= 0;
    int indice = 0;
    Usuario use;
    public FrmCadUsuario() {
        initComponents();
        usu = dao.getUsuarios();
        mostrarDados();
    }
    
    public void mostrarDados(){
        txtId.setText(""+usu.get(indice).getId());
        txtNome.setText(usu.get(indice).getNome());
        txtEndereco.setText(usu.get(indice).getEndereco());
        txtCelular.setText("" + usu.get(indice).getCelular());
        txtSenha.setText(usu.get(indice).getSenha());
        if(use.getStatus().equals("É Admin")){
            rbAdmin.setSelected(true);
        }
        else if(use.getStatus().equals("É cliente")){
            rbCliente.setSelected(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grupoStatus = new javax.swing.ButtonGroup();
        PainelUsuario = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        lblEndereco = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        rbAdmin = new javax.swing.JRadioButton();
        rbCliente = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        PainelUsuario.setBackground(new java.awt.Color(255, 204, 153));

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTitulo.setText("Cadastro do Usuário");

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("Id:");

        lblNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNome.setText("Nome:");

        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        lblEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblEndereco.setText("Endereço:");

        lblCelular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCelular.setText("Celular:");

        lblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha.setText("Senha:");

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setText("Status:");

        txtEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtCelular.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCelular.setText("(  )");

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnUltimo.setText(">|");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        rbAdmin.setBackground(new java.awt.Color(255, 204, 153));
        grupoStatus.add(rbAdmin);
        rbAdmin.setText("É Admin");

        rbCliente.setBackground(new java.awt.Color(255, 204, 153));
        grupoStatus.add(rbCliente);
        rbCliente.setText("É Cliente");

        javax.swing.GroupLayout PainelUsuarioLayout = new javax.swing.GroupLayout(PainelUsuario);
        PainelUsuario.setLayout(PainelUsuarioLayout);
        PainelUsuarioLayout.setHorizontalGroup(
            PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                                .addComponent(lblId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCelular)
                                    .addComponent(lblEndereco))
                                .addGap(162, 162, 162)))
                        .addGap(183, 183, 183))
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblSenha)
                            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                                .addComponent(lblStatus)
                                .addGap(69, 69, 69)
                                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                                        .addComponent(rbAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(rbCliente))
                                    .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(52, 52, 52)
                        .addComponent(btnSalvar))
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnPrimeiro)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior)))
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnEditar)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUsuarioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo)
                        .addGap(42, 42, 42)))
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelUsuarioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluir))
                    .addComponent(btnUltimo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(146, 146, 146))
        );
        PainelUsuarioLayout.setVerticalGroup(
            PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(38, 38, 38)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(rbAdmin)
                    .addComponent(rbCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUltimo)
                    .addComponent(btnProximo)
                    .addComponent(btnAnterior)
                    .addComponent(btnPrimeiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PainelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if(usu.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Não exitem usuarios cadastrados");
        }
        else
        {
            indice=0;
            mostrarDados();
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(usu.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existe usuario cadastrados");
        }
        else{
            indice--;
        }
        if(indice<0){
            indice++;
            JOptionPane.showMessageDialog(null, "Você já esta no primeiro registro");
        }
        mostrarDados();
        btnProximo.setEnabled(true);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if(usu.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Não exitem usuario cadastrados");
        }
        else
        {
            indice++;
            if(indice>usu.size()-1)
            {
                indice--;
                JOptionPane.showMessageDialog(null, "Você já está no último registro");
            }
            mostrarDados();
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if(usu.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Não exitem usuariobooks cadastrados");
        }
        else
        {
            indice=usu.size()-1;
            mostrarDados();
            btnProximo.setEnabled(false);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        
        txtId.setText(""+id);
        txtNome.setText("");
        txtEndereco.setText("");
        txtCelular.setText("");
        txtSenha.setText("");
        

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNome(txtNome.getText());
        usuario.setEndereco(txtEndereco.getText());
        usuario.setCelular(txtId.getText());
        usuario.setSenha(String.valueOf(txtSenha.getPassword()));
        if(rbAdmin.isSelected())
        {
            usuario.setStatus(rbAdmin.getText());
        }
        if(rbCliente.isSelected())
        {
            usuario.setStatus(rbCliente.getText());
        }
        
        dao.salvarUsuario(usuario);
        usu.clear();
        usu = dao.getUsuarios();
        indice=usu.size()-1;
        mostrarDados();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNome(txtNome.getText());
        usuario.setEndereco(txtEndereco.getText());
        usuario.setCelular(txtId.getText());
        usuario.setSenha(String.valueOf(txtSenha.getPassword()));
        if(rbAdmin.isSelected())
        {
            usuario.setStatus(rbAdmin.getText());
        }
        if(rbCliente.isSelected())
        {
            usuario.setStatus(rbCliente.getText());
        }
        
        dao.salvarUsuario(usuario);
        usu.clear();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(usu.isEmpty())
        {
        txtId.setText("");
        txtNome.setText("");
        txtEndereco.setText("");
        txtCelular.setText("");
        txtSenha.setText("");
        grupoStatus.clearSelection();
        
        }else
        {
            int opcao = JOptionPane.showConfirmDialog(null, "Tem ceteza que deseja excluir o usuario"+txtNome.getText(),"Confirmação",JOptionPane.YES_NO_OPTION);
            if(opcao ==0)
            {
                dao.excluirUsuario(Integer.parseInt(txtId.getText()));
                usu.clear();
                usu = dao.getUsuarios();
                indice=usu.size()-1;
                mostrarDados();
                
            }
            else
            JOptionPane.showMessageDialog(null, "Não foi excluído");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelUsuario;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.ButtonGroup grupoStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
