
package view;
import controller.ControllerBebida;
import model.Bebida;
import dao.DaoBebidaImp;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author Kamila Monaris
 */
public class FrmCadBebida extends javax.swing.JInternalFrame {

    //DaoBebidaImp dao = new DaoBebidaImp();
    ControllerBebida control = new ControllerBebida();
    List<Bebida> bebida = new ArrayList<Bebida>();
    
    int indice = 0;
    Bebida bebi;
    
    public void mostrarDados(){
        txtId.setText(""+bebida.get(indice).getId());
        txtDescricao.setText(bebida.get(indice).getDescricao());
    } 
    
    public FrmCadBebida(){
        initComponents();
        txtId.setEnabled(false);
        bebida=control.atualizaListaBebida();
        
        if(bebida.isEmpty()){
            JOptionPane.showMessageDialog(null, "não exite bebida cadastrados");
        
        }
        else{
        mostrarDados();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelBebida = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btmUltimo = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        PainelBebida.setBackground(new java.awt.Color(255, 204, 153));

        lblTitulo.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        lblTitulo.setText("Cadastrar Bebida");

        lblId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblId.setText("Id:");

        lblDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDescricao.setText("Descrição:");

        txtId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDescricao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        btnPrimeiro.setText("|<");
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setText("<<");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setText(">>");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btmUltimo.setText(">|");
        btmUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmUltimoActionPerformed(evt);
            }
        });

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelBebidaLayout = new javax.swing.GroupLayout(PainelBebida);
        PainelBebida.setLayout(PainelBebidaLayout);
        PainelBebidaLayout.setHorizontalGroup(
            PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelBebidaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(146, 146, 146))
            .addGroup(PainelBebidaLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnNovo)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(65, 65, 65))
            .addGroup(PainelBebidaLayout.createSequentialGroup()
                .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelBebidaLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblId)
                            .addComponent(lblDescricao))
                        .addGap(43, 43, 43)
                        .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PainelBebidaLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnPrimeiro)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior)
                        .addGap(27, 27, 27)
                        .addComponent(btnProximo)
                        .addGap(18, 18, 18)
                        .addComponent(btmUltimo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelBebidaLayout.setVerticalGroup(
            PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro)
                    .addComponent(btnAnterior)
                    .addComponent(btnProximo)
                    .addComponent(btmUltimo))
                .addGap(27, 27, 27)
                .addGroup(PainelBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnSalvar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if(bebida.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não existe bebida cadastrados");    
        }
        else{
        indice = 0;
        txtId.setText(""+bebida.get(indice).getId());
        txtDescricao.setText(bebida.get(indice).getDescricao());
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(bebida.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existe bebida cadastrados");
        }
        else{
            indice--;
        }
        if(indice<0){
            indice++;
            JOptionPane.showMessageDialog(null, "Você já esta no primeiro registro");
        }
        mostrarDados();
        btnProximo.setEnabled(true); 
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if(bebida.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existe bebidas cadastrados");
        }
        else{
            indice++;
        }
        if(indice>bebida.size()-1){
            indice--;
            JOptionPane.showMessageDialog(null, "Você ja esta no ultimo registro");
        }
        mostrarDados();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btmUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmUltimoActionPerformed
        if(bebida.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não existe bebidas cadastrados");    
        }
        else{
        indice=bebida.size()-1;
        mostrarDados();
        btnProximo.setEnabled(false);
        }
    }//GEN-LAST:event_btmUltimoActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        txtId.setText("");
        txtDescricao.setText("");
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        bebi =  new Bebida();
        //bebi.setId(Integer.parseInt(txtId.getText()));
        bebi.setDescricao(txtDescricao.getText());
        
        control.inserirBebida(bebi);
        bebida = control.atualizaListaBebida();
        indice = bebida.size()-1;
        mostrarDados();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       if(bebida.isEmpty()){
           txtId.setText("");
           txtDescricao.setText("");
       }else{
        bebi =  new Bebida();
        bebi.setId(Integer.parseInt(txtId.getText()));
        bebi.setDescricao(txtDescricao.getText());
        
        control.EditarBebida(bebi);
        bebida = control.atualizaListaBebida();
        indice = bebida.size()-1;
        mostrarDados();
       
       }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        control.remover(Integer.parseInt(txtId.getText()));
        bebida = control.atualizaListaBebida();
        indice = bebida.size()-1;
        mostrarDados();
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelBebida;
    private javax.swing.JButton btmUltimo;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
